name: Deploy demo to GitHub Pages
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    name: Deploy demo to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm test -- --watchAll=false
      - run: npm run build
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: ghp
          folder: build
